<a href="https://colab.research.google.com/github/Fiarma/Data-Science-Projects/blob/fiarma/Projects_Pharmaceutical_Supply_Chain_Inventory_Optimization_Predicting_Energy_Consumption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Import Packages**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import  mean_absolute_error, mean_squared_error, mean_absolute_percentage_error
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

**2.  Data Exploration  and Preprocessing**

In [ ]:
!pip install gdown
import gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.10/dist-packages (5.1.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown) (3.15.4)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gdown) (4.66.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2024.7.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (1.7.1)

In [ ]:
# load dataset

#https://drive.google.com/file/d/1Q_Dz6gpxGugfly1ZKaN1C-4hTA6at6oQ/view?usp=sharing

file_id = "1Q_Dz6gpxGugfly1ZKaN1C-4hTA6at6oQ"

output_file = 'dataset.csv'

gdown.download(id = file_id, output = output_file, quiet=False)

df = pd.read_csv(output_file)

Downloading...
From: https://drive.google.com/uc?id=1Q_Dz6gpxGugfly1ZKaN1C-4hTA6at6oQ
To: /content/dataset.csv
100%|██████████| 2.09M/2.09M [00:00<00:00, 57.0MB/s]

In [ ]:
df.head()

,Product_ID,Shelf_Life_Days,Sales_2021,Sales_2022,Market_Trend_Factor,Compliance_Status,Supplier_ID,Manufacturing_Location,Product_Category,Safety_Stock_Days,Storage_Location
0,Product_1,277,602.6,545,0.906303,Compliant,Supplier_2,Location_B,Category_B,22,Warehouse_C
1,Product_2,343,359.4,345,0.972500,Compliant,Supplier_1,Location_C,Category_C,24,Warehouse_C
2,Product_3,291,983.0,915,1.026074,Non-compliant,Supplier_5,Location_C,Category_A,24,Warehouse_B
3,Product_4,298,789.4,751,0.911503,Compliant,Supplier_8,Location_C,Category_A,20,Warehouse_B
4,Product_5,260,326.8,430,1.052617,Compliant,Supplier_10,Location_A,Category_B,21,Warehouse_A

In [ ]:
# missing values
df.isnull().sum()

Product_ID                0
Shelf_Life_Days           0
Sales_2021                0
Sales_2022                0
Market_Trend_Factor       0
Compliance_Status         0
Supplier_ID               0
Manufacturing_Location    0
Product_Category          0
Safety_Stock_Days         0
Storage_Location          0
dtype: int64

In [ ]:
# check for duplicated values
df.duplicated().sum()

0

In [ ]:
df.describe()

,Shelf_Life_Days,Sales_2021,Sales_2022,Market_Trend_Factor,Safety_Stock_Days
count,19381.000000,19381.000000,19381.000000,19381.000000,19381.000000
mean,301.737939,618.423250,618.798256,0.999851,21.327073
std,25.576353,239.313199,220.590729,0.257548,7.090764
min,260.000000,80.000000,234.000000,0.078110,6.000000
25%,278.000000,429.000000,429.000000,0.823775,16.000000
50%,302.000000,619.200000,621.000000,1.000239,21.000000
75%,326.000000,811.200000,809.000000,1.175179,27.000000
max,344.000000,1155.400000,999.000000,1.909161,42.000000